DTube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='users')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include

from .views import UserLoginView, UserProfileView, UserLogoutView, UserProfileUpdateView, user_signup, verify_email, \
    resend_otp

app_name = 'users'
urlpatterns = [
    path('', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('index/', UserProfileView.as_view(), name='profile'),
    path('update-profile/', UserProfileUpdateView.as_view(), name='update-profile'),
    path('signup/', user_signup, name='signup'),
    path("verify-email/<slug:username>/<uuid:u_link>/", verify_email, name="verify-email"),
    path("resend-otp/", resend_otp, name="resend-otp"),
    path('videos/', include('videos.urls', namespace='videos')),
]

users/models.py
import uuid

from PIL import Image
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from django.utils import timezone

from .managers import CustomUserManager


# Create your models here.
class CustomUser(AbstractBaseUser, PermissionsMixin):
    first_name = models.CharField(max_length=100, blank=True)
    last_name = models.CharField(max_length=100, blank=True)
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=100, unique=True)
    image = models.ImageField(default='default-avatar.png', upload_to='profile_pics')
    date_joined = models.DateTimeField(default=timezone.now)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['username', ]

    def get_full_name(self):
        if self.first_name and self.last_name:
            return f'{self.first_name.capitalize()} {self.last_name.capitalize()}'
        return self.username

    def get_short_name(self):
        if self.first_name:
            return self.first_name.capitalize()
        return self.username

    def save(self, *args, **kwargs):
        super().save()
        img = Image.open(self.image.path)
        if img.height > 250 or img.width > 250:
            img.thumbnail((250, 250))
            img.save(self.image.path)

    def __str__(self):
        return self.username


class OTP(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    otp = models.CharField(max_length=8)
    created_at = models.DateTimeField(default=timezone.now)
    expires_at = models.DateTimeField()
    u_link = models.UUIDField(default=uuid.uuid4, editable=False)

    def __str__(self):
        return f"{self.user.username}'s OTP"

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm, Form


class CustomUserUpdateForm(ModelForm):
    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'username', 'image',)


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'username', 'password1', 'password2')


class EmailVerificationForm(Form):
    otp = forms.CharField(label='OTP', max_length=8)


class ResendOTPForm(Form):
    email = forms.EmailField(label='Email')

users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model, login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from django.views.generic import UpdateView, ListView

from videos.models import VideoPost
from .forms import CustomUserUpdateForm, CustomUserCreationForm, EmailVerificationForm, ResendOTPForm
from .models import CustomUser, OTP
from .utils import send_otp_email


class UserLoginView(LoginView):
    redirect_authenticated_user = True
    template_name = 'users/login.html'
    success_url = reverse_lazy('users:profile')

    def post(self, request, *args, **kwargs):
        email = self.request.POST.get('username')
        password = self.request.POST.get('password')
        user = authenticate(request, username=email, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                messages.success(self.request, 'You are now logged in.')
                return redirect('users:profile')
            else:
                try:
                    otp_obj = OTP.objects.get(user=user, expires_at__gte=timezone.now())
                    messages.warning(request, 'Please check your email and enter your OTP to activate your account.')
                    return redirect(
                        reverse('users:verify-email', kwargs={'username': user.username, 'u_link': otp_obj.u_link}))
                except OTP.DoesNotExist:
                    messages.warning(self.request,
                                     'Your account is not active. Please verify your email and try again.')
                    return redirect('users:resend-otp')
        messages.error(self.request, 'Invalid email or password.')
        return redirect('users:login')


class UserProfileView(LoginRequiredMixin, ListView):
    template_name = 'users/index.html'
    context_object_name = 'videos'
    extra_context = {'section': 'my_videos'}
    paginate_by = 5
    paginate_orphans = 1

    def get_queryset(self):
        user = get_object_or_404(CustomUser, pk=self.request.user.pk)
        return VideoPost.objects.filter(author=user)


class UserProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = CustomUserUpdateForm
    template_name = 'users/update_profile.html'
    success_url = reverse_lazy('users:profile')

    def form_valid(self, form):
        messages.info(self.request, 'Your profile has been updated!')
        return super().form_valid(form)

    def get_object(self, queryset=None):
        return self.request.user


class UserLogoutView(LogoutView):
    template_name = 'users/logout.html'


def user_signup(request):
    if request.user.is_authenticated:
        messages.info(request, 'You are already a logged in user.')
        return redirect('users:profile')
    # form = CustomUserCreationForm(request.POST or None)
    form = CustomUserCreationForm()
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            u_link = OTP.objects.filter(user=user).first().u_link
            messages.success(request, "Account created successfully! An OTP was sent to your Email")
            return redirect('users:verify-email', username=user.username, u_link=u_link)
    return render(request, 'users/signup.html', {'form': form})


def verify_email(request, username, u_link):
    if request.user.is_authenticated:
        messages.warning(request, 'You are already a logged in user.')
        return redirect('users:profile')
    user = get_object_or_404(CustomUser, username=username)
    user_otp = get_object_or_404(OTP, user=user, u_link=u_link)
    if request.method == 'POST':
        if user_otp.otp == request.POST.get('otp'):
            if user_otp.expires_at > timezone.now():
                user.is_active = True
                user.save()
                user_otp.delete()
                messages.success(request, 'Your account has been verified! You can login now.')
                return redirect('users:login')
            else:
                user_otp.delete()
                messages.warning(request, 'Your OTP has been expired! Request a new OTP.')
                return redirect('users:resend-otp')
        else:
            u_link = OTP.objects.filter(user=user).first().u_link
            messages.error(request, 'Invalid OTP!')
            return redirect('users:verify-email', username=user.username, u_link=u_link)
    if user_otp.expires_at < timezone.now():
        user_otp.delete()
        messages.warning(request, 'Your OTP has been expired! Request a new OTP.')
        return redirect('users:resend-otp')
    return render(request, 'users/verify.html', {'form': EmailVerificationForm()})


def resend_otp(request):
    if request.user.is_authenticated:
        messages.info(request, 'You are already a logged in user.')
        return redirect('users:profile')
    if request.method == 'POST':
        email = request.POST.get('email')
        try:
            user = CustomUser.objects.get(email=email)
        except CustomUser.DoesNotExist:
            messages.warning(request, 'Email does not exist on server. Enter a valid email.')
            return redirect('users:resend-otp')
        if user.is_active:
            messages.warning(request, 'Your account is already activated.')
            return redirect('users:login')
        OTP.objects.filter(user=user).delete()
        send_otp_email(user)
        u_link = OTP.objects.filter(user=user).first().u_link
        messages.success(request, 'Your OTP has been sent to your Email')
        return redirect('users:verify-email', username=user.username, u_link=u_link)
    return render(request, 'users/resend_otp.html', {'form': ResendOTPForm()})

users/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'users/css/base.css' %}">
</head>
<body>
{% include 'header.html' %}
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li class="{{ message.tags }}">
                {{ message|safe }}
            </li>
        {% endfor %}
    </ul>
{% endif %}
<div id="content">
    {% block content %}

    {% endblock %}
</div>
</body>
</html>

users/templates/header.html
<div id="header">
    <span class="logo">DTube</span>
    {% if request.user.is_authenticated %}
        <ul class="menu">
            <li {% if section == "my_videos" %}class="selected"{% endif %}>
                <a href="{% url "users:profile" %}">My Videos</a>
            </li>
            <li {% if section == "all_videos" %}class="selected"{% endif %}>
                <a href="{% url 'users:videos:all_video_posts' %}">All Videos</a>
            </li>
        </ul>
    {% endif %}
    <span class="user">
        {% if request.user.is_authenticated %}
            Hello {{ request.user.get_short_name }},
            <a href="{% url "users:update-profile" %}">Update-Profile</a>
            <form action="{% url 'users:logout' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="button-link">Log-Out</button>
            </form>
        {% else %}
            <a href="{% url "users:login" %}">Log-in</a>
            <a href="{% url "users:signup" %}">Sign-up</a>
        {% endif %}
    </span>
</div>

users/templates/pagination.html
{% if page.has_previous %}
    <a href="?page={{ page.previous_page_number }}">Previous</a>
{% endif %}
<span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
{% if page.has_next %}
    <a href="?page={{ page.next_page_number }}">Next</a>
{% endif %}

users/templates/profile_detail.html
<div class="card">
    <img src="{{ request.user.image.url }}" alt="Profile Picture">
    <div class="user-details">
        <h3>{{ request.user.get_full_name }}</h3>
        Email : {{ request.user.email }}<br>
        Username : {{ request.user.username }}<br>
        Date Joined : {{ request.user.date_joined }}
    </div>
</div>